[tools]
java = "latest"
jq = "latest"
maven = "latest"
python = "3"
uv = "latest"

[tasks.generate]
description = "Generate the keyboard files"
run = "mvn compile exec:java"

[tasks.flash]
description = "Flash the keyboard"
depends = "generate"
run = "uv run qmk flash -kb ferris/sweep -km zeitlinger -bl avrdude-split-left"
